# -*- coding: utf-8 -*-
"""fibo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFcvcmd0c-UlF6dQEEN4DdnA1YgfBkTI
"""

def fib(n):
   
    a, b = 0.0, 1.0
    for i in range(n):
        a, b = a + b, a
    return a

if __name__ == '__main__': 
    import sys
    arg, numiter = map(int, sys.argv[1:]) 
    for i in range(numiter):
        fib(arg)