# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BdFdM2yIYZlStgA297AKJDdF3l4BVlGs
"""

from distutils.core import setup
from Cython.Build import cythonize
setup(ext_modules =cythonize('cy_fibo.pyx'))