# -*- coding: utf-8 -*-
"""time

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UhDg4u8ndRAseDi9cBy-eu9n1Vx-UL3Q
"""

from timeit import repeat
from subprocess import check_output
def timer(arg, niter, name, module):
    stmt = "%s(%s)" % (name, arg)
    setup = "from %s import %s" % (module, name)
    time = min(repeat(stmt=stmt, setup=setup,
    number=niter)) / float(niter) * 1e9
    return time

N = 10**6
pytime_0 = timer(0, N, name='fib', module='fib')
cytime_0 = timer(0, N, name='fib', module='cyfib')
ctime_0 = float(check_output(('./cfib.x 0 %d' %
N).split()))
py0speedup = 1.0
cy0speedup = pytime_0 / cytime_0
c0speedup = pytime_0 / ctime_0


N = 10**6
pytime_120 = timer(120, N, name='fib', module='fib')
cytime_120 = timer(120, N, name='fib',
module='cyfib')
ctime_120 = float(check_output(('./cfib.x 120 %d' %
N).split()))
py120speedup = 1.0
cy120speedup = pytime_120 / cytime_120

c120speedup = pytime_120 / ctime_120


pytime_160 = timer(160, N, name='fib', module='fib')
cytime_160 = timer(160, N, name='fib',
module='cyfib')
ctime_160 = float(check_output(('./cfib.x 160 %d' %N).split()))
py160speedup = 1.0
cy160speedup = pytime_160 / cytime_160

c160speedup = pytime_160 / ctime_160


pytime_200 = timer(200, N, name='fib', module='fib')
cytime_200 = timer(200, N, name='fib',
module='cyfib')
ctime_200 = float(check_output(('./cfib.x 180 %d' %
N).split()))
py200speedup = 1.0
cy200speedup = pytime_200 / cytime_200

c200speedup = pytime_200 / ctime_200

data_format = "{:s},{:.0f},{:.1f},{:.0f},{:.1f},{:.0f},{:.1f},{:.0f},{:.1f},{:.0f},{:.1f}\n"

with open("fib0.csv", 'w') as fh:
    fh.write("Version,fib(0) runtime [ns],speedup,fib(120) runtime [ns],speedup 120,fib(160) runtime [ns],speedup 160,fib(200) runtime [ns],speedup 200\n")
    fh.write(data_format.format("Python", pytime_0, pytime_120, py120speedup,pytime_160,py160speedup,pytime_200,py200speedup))
    fh.write(data_format.format("Cython", cytime_0, cy0speedup, cytime_120,cy120speedup,cytime_160,cy160speedup,cytime_200,cy200speedup))
    fh.write(data_format.format("Pure C", ctime_0, c0speedup,ctime_120,c120speedup,ctime_160,c160speedup,ctime_200,c200speedup))